### PR TITLE
Launcher which updates itself and Moonwards using md5 hashes.

### PR DESCRIPTION
**Pull request by Gyrth**
This is my first attempt at it. These are the steps that it takes:

1. It gets a JSON file on my Apache server which contains a list of launcher files.
2. It picks the files for the relevant platform.
3. Then gets all the md5 files that are in the same directory. [filename].md5
4. These md5 hashes are checked against the local files.
5. If there are launcher updates, it will download those and restart the launcher.

The same thing happens with the Moonwards files. But it will ask to update and launch.

I have not had the chance to test it on Windows or OSX yet. So we would need to work together to find out what ``execute`` parameters are needed.

### CODE REVIEW

**Comment by Gyrth** [comment]
The launcher is updated by replacing the current launcher executable and pck file. It seems to work flawlessly btw. 

However Moonwards is written to the user directory. So that means the launcher can be in any directory, but Moonwards will always be in ``user://``.

**Comment by Gyrth** [comment]
I've also added a bash script that writes a .md5 file for each file in the Export directory. So that means the launcher project can be exported, hashed and uploaded to the server in a few minutes.

**Comment by Gyrth** [comment]
The server I'm using is over [here](http://107.173.129.154/moonwards/). So you can check out the JSON files and the folder structure.

**Comment by TheDuriel** [comment]
Merging so folks can see whats going on. Still WIP ofc.

**Pull request merged**
